import "./globals.css";
import type { Metadata } from "next";
import Head from "next/head";
import localFont from "next/font/local";
import { StateContext } from "./context/stateContext";

const satoshi = localFont({
  src: [
    {
      path: "../public/Satoshi-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/Satoshi-Bold.woff2",
      weight: "700",
    },
    {
      path: "../public/Satoshi-Black.woff2",
      weight: "800",
    },
    {
      path: "../public/Satoshi-Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/Satoshi-Light.woff2",
      weight: "200",
    },
    {
      path: "../public/Satoshi-Variable.woff2",
      weight: "100",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${satoshi.className} top-0`}>
        <StateContext>{children}</StateContext>
      </body>
    </html>
  );
}
